# Try PCL
FIND_PACKAGE(PCL)
if(PCL_FOUND)
    message("-- PCL FOUND --")
    ADD_DEFINITIONS(-DWITHPCL)
    INCLUDE_DIRECTORIES(${PCL_INCLUDE_DIRS})
    LINK_DIRECTORIES(${PCL_LIBRARY_DIRS})
    ADD_DEFINITIONS(${PCL_DEFINITIONS})
endif()
